Django/mypyweb/blogs/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'), # 목록
    path('<int:post_id>/', views.detail, name='detail'), # 상세 페이지
    path('post/create/', views.post_create, name='post_create'),
    path('category/<str:slug>/', views.category_page,
         name='category_page'), # 카테고리별 페이지
]

Django/mypyweb/blogs/common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

Django/mypyweb/blogs/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index), # http://127.0.0.1:8000/
    path('blog/', include('blog.urls')),
    path('common/', include('common.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

Django/mypyweb/blogs/blog/models.py
from django.contrib.auth.models import User
from django.db import models

from django.urls import reverse

import os


# 카테고리 모델
class Category(models.Model):
    # unique=True 중복 불허
    name = models.CharField(max_length=50, unique=True)
    # url 주소 - 문자, allow_unicode - 한글 허용
    slug = models.SlugField(max_length=200, unique=True,
                allow_unicode=True)

    def __str__(self):
        return self.name

    # 카테고리 url 주소
    def get_absolute_url(self):
      #return f'/blog/category/{self.slug}' #절대경로
      # reverse() - redirect 유사: app-name 경로 이동
        return  reverse('blog:category_page', args=[self.slug]) 

    # 관리자 페이지에서 적용 - verbose_name_plural(복수형)
    class Meta:
        ordering = ['name']  # 이름순 정렬
        verbose_name = 'category'
        verbose_name_plural = 'categories'

# 포스트 모델
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)    # 제목
    content = models.TextField()                # 내용
    pub_date = models.DateTimeField()           # 발행일
    modify_date = models.DateTimeField(null=True, blank=True)   # 입력 폼이 비어도 됨
    photo = models.ImageField(upload_to='blog/images/%Y/%m/%d/',
                    null=True, blank=True)  # null 허용, 파일을 첨부하지 않을 수 있음
    file = models.FileField(upload_to='blog/files/%Y/%m/%d/',
                            null=True, blank=True) # null 허용, 파일을 첨부하지 않을 수 있음
    # models.SET_NULL: 카테고리가 삭제되어도 카테고리가 없는 포스트는 유지
    category = models.ForeignKey(Category, null=True, blank=True,
                    on_delete=models.SET_NULL)  # 카테고리가 삭제되어도

    def __str__(self):
        return self.title

    # 파일의 이름 출력
    def get_file_name(self):
        return os.path.basename(self.file.name)

    # 파일의 확장자 구분
    def get_file_ext(self):
        # seoul.scv -> [seoul, csv]
        return self.get_file_name().split().split('.')[-1]

Django/mypyweb/blogs/blog/forms.py
from django import forms
from blog.models import Post

# 포스트 폼 생성
class PostForm(forms.ModelForm):
    class Meta:
        model = Post    # Post 객체 생성
        fields = ['title', 'content', 'photo', 'file', 'category']
        labels = {
            'title': '제목',
            'content': '내용',
            'photo': '사진',
            'file': '파일',
            'category': '분류'
        }

Django/mypyweb/blogs/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# UserCreationForm을 상속받은 UserForm 정의함
class UserForm(UserCreationForm):
    email = forms.EmailField(label='이메일')

    class Meta: # 중첩 클래스
        model = User
        fields = ('username', 'email')  # 튜플 구조

Django/mypyweb/blogs/blog/views.py
from django.shortcuts import render, redirect
from django.utils import timezone

from blog.forms import PostForm
from blog.models import Post, Category

def index(request):
    return render(request, 'blog/index.html')

# 포스트 목록
def post_list(request):
    post_list = Post.objects.order_by('-pub_date')  # 포스트 전체 검색
    categories = Category.objects.all()   # 카테고리 전체 검색
    context = {'post_list': post_list, 'categories': categories}
    return render(request, 'blog/post_list.html', context)

# 상세 페이지
def detail(request, post_id):
    post = Post.objects.get(id=post_id)
    categories = Category.objects.all() # 카테고리 전체 검색
    context = {'post': post, 'categories': categories}
    return render(request, 'blog/detail.html', context)

# 글쓰기
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES) # (일반속성 ,파일)
        if form.is_valid(): # 유효하다면
            post = form.save(commit=False)
            post.pub_date = timezone.now() # 현재 시간
            post.author = request.user  # 로그인한 사람이 글쓴이임
            post.save()
            return redirect('blog:post_list')
    else:
        form = PostForm()   # 비어있는 폼
    context = {'form': form}
    return render(request, 'blog/post_form.html', context)

# 카테고리 페이지 처리 메서드
def category_page(request, slug):
    current_category = Category.objects.get(slug=slug)  # 현재 카테고리 검색
    post_list = Post.objects.filter(category=current_category)  # 현 카테고리의 포스트들
    post_list = post_list.order_by('-pub_date') # 날짜순 내림차순
    categories = Category.objects.all() # 전체 카테고리
    context = {
        'current_category': current_category,
        'post_list': post_list,
        'categories': categories
    }
    return render(request, 'blog/post_list.html', context)

Django/mypyweb/blogs/common/views.py
from django.shortcuts import render, redirect
from .forms import UserForm

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)   # 폼에 입력된 데이터를 넘겨 받음
        if form.is_valid():
            form.save() # db 저장
            return redirect('/')
    else:
        form = UserForm()
    context = {'form': form}
    return render(request, 'common/signup.html', context)

Django/mypyweb/blogs/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <script src="{% static 'blog/js/bootstrap.js' %}"></script>
    <script src="https://kit.fontawesome.com/cf70e4dc4a.js" crossorigin="anonymous"></script>
</head>
<body>
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</body>
</html>

Django/mypyweb/blogs/templates/blog/detail.html
{% extends 'base.html' %}
{% block title %}포스트 상세 내용입니다.
{% endblock %}
{% block content %}
<div class="container my-3">
    <section id="detail">
        {% if post.category %}
        <h6 class="text-end">[{{ post.category }}]</h6>
        {% endif %}
        <h3>{{ post.title }}</h3>
        <h5 style="white-space: pre-line; line-height: 1.5">
            {{ post.content }}
        </h5>
        <p>글쓴이: {{ post.author }} (작성일: {{ post.pub_date }})</p>
        <!-- 이미지 파일이 있으면 보이기 -->
        {% if post.photo %}
        <img src="{{ post.photo.url }}">
        {% endif %}
        <!-- 파일이 있으면 보이기 -->
        {% if post.file %}
        <p>
            <!-- 다운로드 자동완성 -->
            <a href="{{ post.file.url }}" class="btn btn-outline-dark">
                {% if post.get_file_ext == 'csv' %}
                    <i class="fa-solid fa-file-csv"></i>
                {% elif post.get_file_ext == 'excel' or post.get_file.ext == 'xls' %}
                    <i class="fa-solid fa-file-excel"></i>
                {% else %}
                    <i class="fa-solid fa-file"></i>
                {% endif %}
                {{ post.get_file_name }}</a>
        </p>
        {% endif %}

    </section>
    <aside id="category">
        <h4>분류(Category)</h4>
        <div>
            <ul>
                {% for category in categories %}
                <li>{{ category.name }}({{ category.post_set.count }})</li>
                {% endfor %}
            </ul>
        </div>
    </aside>
</div>
{% endblock %}

Django/mypyweb/blogs/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Welcome~ MyBlog!!
{% endblock %}
{% block content %}
<div class="container my-3 text-center">
    <h1>Blog에 오신 것을 환영합니다.</h1>
    <div class="my-3">
        <img src="{% static 'blog/images/activity.jpg' %}" alt="패러글라이딩">
    </div>
    </div>
{% endblock %}

Django/mypyweb/blogs/templates/blog/post_form.html
{% extends 'base.html' %}
{% block title %}글쓰기 폼입니다.
{% endblock %}
{% block content %}
<div class="container my-3">
    <h3>글쓰기</h3>
    <form action="" method="post"
          enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }} <!-- blog forms.py -->
        <button type="submit">저장하기</button>
    </form>
</div>
{% endblock %}

Django/mypyweb/blogs/templates/blog/post_list.html
{% extends 'base.html' %}
{% block title %}포스트 목록입니다.
{% endblock %}
{% block content %}
<div class="container">
    <section id="post_list">
    <h2>Blog 홈</h2>
    {% if post_list %}
        <!-- 포스트 가져옴 -->
        {% for post in post_list %}
            <hr>
            {% if post.category %}
                <h6 class="text-end">[{{ post.category }}]</h6>
            {% endif %}
            <h3 class="my-3">
                <a href="{% url 'blog:detail' post.id %}">
                    {{ post.title }}
                </a>
            </h3>
            <h5 style="white-space: pre-line; line-height: 1.5">
                {{ post.content }}
            </h5>
            <p>글쓴이: {{ post.author }} (작성일: {{ post.pub_date }}</p>
            {% if post.photo %}
                <img src="{{ post.photo.url }}">
            {% endif %}
        {% endfor %}
    {% else %}
        <p>포스트가 없습니다.</p>
    {% endif %}
    </section>
    <aside id="category">
        <h4>분류(Category)</h4>
        <div>
            <ul>
                {% for category in categories %}
                    {% if current_category.slug == category.slug %}
                <!-- category.post_set.count : 포스트의 총 개수 -->
                <li style="background: #ff0">
                    <a href="{{ category.get_absolute_url }}">
                        {{ category.name }}({{ category.post_set.count }})
                    </a>
                </li>
                {% else %}
                <li>
                    <a href="{{ category.get_absolute_url }}">
                        {{ category.name }}({{ category.post_set.count }})
                    </a>
                </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </aside>
</div>
{% endblock %}

Django/mypyweb/blogs/templates/common/login.html
{% extends 'base.html' %}
{% block title %}로그인 폼입니다.
{% endblock %}
{% block content %}
<div class="container">
  <section id="login">
      <div class="row">
          <div class="col-4">
              <h4>로그인</h4>
          </div>
          <div class="col-8 text-end">
              <span>
                  또는 <a href="{% url 'common:signup' %}">계정을 만드세요</a>
              </span>
          </div>
      </div>
      <!-- 로그인 폼 -->
      <form action="" method="post">
          {% csrf_token %}
          {% include 'form_errors.html' %}
          <div class="form-group">
              <label for="username">사용자ID</label>
              <input type="text" id="username" name="username"
                     class="form-control"
                     value="{{ form.username.value|default_if_none:'' }}">
          </div>
          <div class="form-group">
              <label for="password">비밀번호</label>
              <input type="password" id="password" name="password"
                     class="form-control"
                     value="{{ form.password.value|default_if_none:'' }}">
          </div>
          <button type="submit" class="btn btn-primary mt-2">로그인</button>
      </form>
  </section>
</div>
{% endblock %}

Django/mypyweb/blogs/templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <section id="login">
      <div class="row">
        <div class="col-4">
            <h4>회원 가입</h4>
        </div>
        <div class="col-8 text-end">
            <span>
                또는 <a href="{% url 'common:login' %}">로그인 하세요</a>
            </span>
        </div>
      </div>
      <!-- 회원가입 폼 -->
      <form action="" method="post">
          {% csrf_token %}
          {% include 'form_errors.html' %}
          <div class="form-group my-2">
             <label for="username" class="mb-1">사용자ID</label>
             <input type="text" id="username" name="username"
                    class="form-control"
                    value="{{ form.subject.value|default_if_none:'' }}">
      </div>
          <div class="form-group my-2">
            <label for="password1" class="mb-1">비밀번호</label>
            <input type="password" id="password1" name="password1"
                class="form-control"
                value="{{ form.password1.value|default_if_none:'' }}">
      </div>
      <div class="form-group my-2">
          <label for="password2" class="mb-1">비밀번호 확인</label>
          <input type="password" id="password2" name="password2"
                 class="form-control"
                 value="{{ form.password2.value|default_if_none:'' }}">
      </div>
          <div class="form-group my-2">
          <label for="last_name" class="mb-1">이름</label>
          <input type="text" id="last_name" name="last_name"
                 class="form-control"
                 value="{{ form.last_name.value|default_if_none:'' }}">
      </div>
          <div class="form-group my-2">
          <label for="email" class="mb-1">이메일</label>
          <input type="text" id="email" name="email"
                 class="form-control"
                 value="{{ form.email.value|default_if_none:'' }}">
      </div>
      <button type="submit" class="btn btn-primary mt-2">가입하기</button>
      </form>
  </section>
</div>
{% endblock %}

Django/mypyweb/blogs/templates/form_errors.html
<!-- 유효성 검사 - 오류 처리 시작-->
{% if form.errors  %}
    {% for field in form %}  <!-- 폼을 필드를 순회하면서 -->
        {% if field.errors  %} <!-- 필드에 오류가 있으면 -->
        <div class="alert alert-danger">
            <strong>{{ field.label }}</strong>
            {{ field.errors }}  <!-- 에러 출력 -->
         </div>
        {% endif %}
    {% endfor %}

    <!-- 넌 필드 오류-->
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}
<!-- 오류 처리 끝-->

Django/mypyweb/blogs/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">PyBlog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'common:login' %}">
            <i class="fa-solid fa-right-to-bracket"></i> 로그인</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'common:logout' %}">
            {{ user.username }}(로그아웃)
          </a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_create' %}">글쓰기</a>
        </li>
      </ul>
    </div>
  </div>
</nav>