Django/mypyweb/pyweb/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.question_list, name='question_list'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('question/create/', views.question_create, name='question_create'), # 질문등록
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'), # 답변등록
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'), # 질문수정
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'), # 질문삭제
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),# 답변삭제
]

Django/mypyweb/pyweb/common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from common import views

app_name = 'common'

urlpatterns = [
    # 클래스형 LoginView를 사용
    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # 함수형 view 작성
    path('signup/', views.signup, name='signup'),
]

Django/mypyweb/pyweb/config/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index), #http://127.0.0.1:8000/
    path('board/', include('board.urls')), #http://127.0.0.1:8000/board
    path('common/', include('common.urls')), #http://127.0.0.1:8000/common
]

Django/mypyweb/pyweb/board/models.py
from django.contrib.auth.models import User
from django.db import models


class Question(models.Model):
    subject = models.CharField(max_length=200)  # 제목
    content = models.TextField()  # 질문 내용
    create_date = models.DateTimeField()  # 등록일
    author = models.ForeignKey(User,on_delete=models.CASCADE) # 글쓴이
    modify = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject


# 답변 모델(테이블)
class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE) # 글쓴이
    content = models.TextField()  # 답변 내용
    create_date = models.DateTimeField()  # 등록일
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question,on_delete=models.CASCADE)  # 외래키

    def __str__(self):
        return self.content

Django/mypyweb/pyweb/board/forms.py
from django import forms
from board.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject' : '제목',
            'content' : '내용'
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content' : '답변 내용'
        }

Django/mypyweb/pyweb/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    last_name = forms.CharField(max_length=20)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "last_name", "email"]

Django/mypyweb/pyweb/board/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from board.models import Question, Answer
from board.forms import QuestionForm, AnswerForm
from django.utils import timezone

def index(request):
    return render(request, "board/index.html")
    # return HttpResponse("<h1>웹 메인 페이지 입니다.</h1>")

# 질문 목록
def question_list(request):
    #question_list = Question.objects.all()
    question_list = Question.objects.order_by('-create_date') #내림 차순
    # 페이지 처리
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '') #검색어

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) | #제목검색
            Q(content__icontains=kw) | #내용검색
            Q(author__username__icontains=kw) | #질문글쓴이
            Q(answer__author__username__icontains=kw) | #답변글쓴이
            Q(answer__content__icontains=kw) #답변내용 검색

        ).distinct() #중복제거

    paginator = Paginator(question_list, 10) # 페이지당 게시글 -10
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'kw':kw}
    return render(request, 'board/question_list.html', context)

def detail(request, question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id) # 데이터가 없으면 404 처리
    context = {'question' : question}
    return render(request, 'board/detail.html', context)

# 질문 등록
@login_required(login_url='common:login') # 로그인 페이지로 이동
def question_create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST) # 입력된 데이터가 있는 폼
        if form.is_valid(): # 폼이 유효성 검사를 통과했다면
            question = form.save(commit=False) #가저장
            question.author = request.user # 세션 권한(로그인한) 있는 글쓴이
            question.create_date = timezone.now()  #등록일 생성
            form.save() #진짜로 저장
            return redirect('board:question_list') # 질문 목록 페이지 이동
            
    else:  #get 방식
        form = QuestionForm()  #폼 객체 생성(빈 폼 생성)
    context = {'form': form}
    return render(request, 'board/question_form.html', context) #get 방식

def answer_create(request, question_id):
    #답변 등록
    #question = Question.objects.get(id=question_id) #해당 id의 질문 객체 생성
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST) #입력값 전달받음
        if form.is_valid():
            answer = form.save(commit=False)  #내용만 저장됨
            answer.create_date = timezone.now() #작성일
            answer.author = request.user #세션 발급
            answer.question = question  #외래키 질문 저장
            answer.save()
            return redirect('board:detail', question_id=question.id)
    else:
        form= AnswerForm()
    context = {'question':question,'form':form}
    return render(request, 'board/detail.html', context)
# 질문수정
@login_required(login_url='common:login')
def question_modify(request, question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('board:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'board/question_form.html', context)

# 질문 삭제
@login_required(login_url='common:login')
def question_delete(request, question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    question.delete()
    return redirect('board:question_list')

# 답변 삭제
@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    answer.delete()
    return redirect('board:detail', question_id=answer.question.id)

Django/mypyweb/pyweb/common/views.py
from django.shortcuts import render, redirect
from common.forms import UserForm

from django.contrib.auth import authenticate, login


# 회원 가입
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST) # 데이터가 입력된 폼
        if form.is_valid():
            form.save() # 회원 가입 db에 저장
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user) #자동 로그인
            return redirect('/') #index 페이지로 이동
    else:
        form = UserForm() #빈폼 생성
    context = {'form': form}
    return render(request, 'common/signup.html', context)

Django/mypyweb/pyweb/templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>hello~</title>
    <link rel="stylesheet" href="{% static 'board/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'board/css/style.css' %}">
    <script src="{% static 'board/js/bootstrap.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
</head>
<body>
{% include 'navbar.html' %}
<!--    본문 내용 start-->
{% block content %}

{% endblock %}
<!--본문 내용 end-->

<!-- 제이쿼리 영역 -->
{% block script %}

{% endblock %}
</body>
</html>

Django/mypyweb/pyweb/templates/board/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <section id="detail">
        <h2 class="border-bottom py-2">{{ question.subject }}</h2>
        <div class="card my-3">
            <div class="card-body">
                <!-- 줄바꿈 style="white-space: pre-line"-->
                <div class="card-text" style="white-space: pre-line">
                    {{ question.content }}  <!-- 질문 내용 -->
                </div>
                <div class="d-flex justify-content-end">
                    <div class="badge bg-info text-start">
                        <div class="mb-2">{{ question.author }}</div>
                        <div>{{ question.create_date }}</div>
                    </div>
                </div>
                <!-- 글쓴이가 로그인한 사람과 일치하면 -->
                {% if question.author == request.user %}
                <div>
                    <a href="{% url 'board:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="#"
                       data-uri="{% url 'board:question_delete' question.id %}"
                       class="delete btn btn-sm btn-online-secondary">삭제</a>
                </div>
                {% endif %}
            </div>
        </div>
        <h5 class="border-bottom my-3 py-2">
            {{ question.answer_set.count }} 개의 답변이 있습니다.
        </h5>
        {% for answer in question.answer_set.all %}
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line">
                    {{ answer.content }}    <!-- 답변 내용 -->
                </div>
                <div class="d-flex justify-content-end">
                    <div class="badge bg-dark text-start">
                        <div class="mb-2">{{ answer.author }}</div>
                        <div>{{ answer.create_date }}</div>
                    </div>
                </div>
                <!-- 글쓴이가 로그인한 사람과 일치하면 -->
                {% if answer.author == request.user %}
                <div>
                    <a href="#"
                       data-uri="{% url 'board:answer_delete' answer.id %}"
                       class="delete btn btn-sm btn-online-secondary">삭제</a>
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}

        <!-- 답변 등록 폼 -->
        <form action="{% url 'board:answer_create' question.id %}"
                        method="post">
            {% csrf_token %} <!-- 필수 : 403 권한 데러 발생 -->
            {% include 'form_errors.html' %}
            <div class="form-group">
                <textarea name="content" rows="10"
                          cols="50" class="form-control mb-3"
                    {% if not user.is_authenticated %}disabled{% endif %}></textarea>
            </div>
            <button type="submit" class="btn btn-primary">답변 등록</button>
        </form>
    </section>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function(){
        $('.delete').click(function(){  // 삭제 버튼을 클릭하면
            if(confirm('정말 삭제하시겠습니까?')){
                location.href=$(this).data('uri');  // 현재 대상 객체의 주소를 이동
            }
        });
    });
</script>
{% endblock %}

Django/mypyweb/pyweb/templates/board/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h1>pyweb에 오신 걸 환영합니다.</h1>
</div>
{% endblock %}

Django/mypyweb/pyweb/templates/board/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <section id="question_form">
        <h4 class="border-bottom pb-2">질문 등록</h4>
        <form action="" method="post">
            {% csrf_token %}
            <!--{{ form.as_p }}--> <!-- input, textarea 태그 포함 -->
            <!-- 유효성 검사 - 오류 처리 시작 -->
            {% if form.errors %}
                <div class="alert alert-danger">
                {% for field in form %}   <!-- 폼을 필드를 순회하면서  -->
                    {% if field.errors %} <!-- 필드에 오류가 있으면 -->
                        {{ field.label }}
                        {{ field.errors }}  <!-- 에러 출력 -->
                    {% endif %}
                {% endfor %}
                </div>
            {% endif %}
            <!-- 오류 처리 끝-->
            <div class="form-group">
                <label for="subject">제목</label>
                <input type="text" id="subject" name="subject" class="form-control"
                       value="{{ form.subject.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="content">내용</label>
                <textarea id="content" name="content" rows="10"
                          class="form-control mb-3">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">등록</button>
        </form>
    </section>
</div>
{% endblock %}

Django/mypyweb/pyweb/templates/board/question_list.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content%}
<div class="container my-3">
    <section id="question_list">
        <!-- 검색 입력 상자 -->
        <div class="row mb-2 justify-content-end">
            <div class="col-6"></div>
                <div class="col-4 d-flex justify-content-end">
                    <input type="text" class="kw form-control"
                        value="{{ kw }}">
                <div class="col-2 input-group-append mx-1">
                    <button type="button" id="btn_search"
                        class="btn btn-outline-secondary">찾기</button>
                </div>
            </div>
        </div>

        <!-- 질문/답변 목록 -->
        <table class="table">
            <thead>
                <tr class="table-primary">
                    <th>번호<th>제목</th><th>작성일시</th><th>글쓴이</th>
                </tr>
            </thead>
            <tbody>
                {% if question_list%}
                    {% for question in question_list %}
                    <tr>
                        <!-- <td>{{ forloop.counter|add:3 }}</td> --> <!-- 1부터 번호 시작 -->
                        <!-- 탬플릿 태그 -->
                        <!-- 1페이지 13~, 2페이지 3~1
                             13 - 1(시작인덱스1, 11, 21) - (0~9:현재 인덱스) + 1 = 13
                             question_list.count - 전체 게시글 수
                         -->
                        <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
                        <td>
                            <a href="{% url 'board:detail' question.id %}">
                               {{ question.subject }}
                            </a>
                        </td>
                        <td>{{ question.create_date }}</td>
                        <td>{{ question.author }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td>질문이 없습니다.</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
        <!-- 페이지 처리 영역 -->
        <ul class="pagination justify-content-center">
            <!-- 이전 페이지 -->
            {% if question_list.has_previous %}
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ question_list.previous_page_number }}">&laquo;</a>
                </li>
            {% else %}
                <!-- 이전 페이지가 없어도 표시됨 -->
                 <li class="page-item disabled">
                    <a class="page-link" href="#">&laquo;</a>
                </li>
            {% endif %}
            <!-- 현재 페이지 -->
            {% for page_number in question_list.paginator.page_range %}
                <!-- 현재 페이지와 리스트의 페이지가 일치하면 활성화함 -->
                {% if page_number == question_list.number %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">
                        {{ page_number }}
                    </a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">
                        {{ page_number }}
                    </a>
                </li>
                {% endif %}
            {% endfor %}
            <!-- 다음 페이지 -->
            {% if question_list.has_next %}
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ question_list.next_page_number }}">&raquo;</a>
                </li>
            {% else %}
                <!-- 이전 페이지가 없어도 표시됨 -->
                 <li class="page-item disabled">
                    <a class="page-link" href="#">&raquo;</a>
                </li>
            {% endif %}
        </ul>
        <!-- 페이지 처리 끝 -->
        <!-- 질문 등록 메뉴 -->
        <a href="{% url 'board:question_create' %}"
            class="btn btn-primary">질문 등록</a>
        <!-- 검색 폼 만들기 -->
        <form action="" method="get" id="searchForm">
            {% csrf_token %}
            <input type="hidden" id="kw" name="kw" value="{{ kw }}">
        </form>
    </section>
</div>
{% endblock %}

{% block script %}
<script>
    $(function(){
        // 검색 처리
        $('#btn_search').click(function(){
            $('#kw').val($('.kw').val());   // 입력폼에서 입력된 키워드를 hidden 타입
            $('#searchForm').submit();      // 폼을 전송함 - view로
        });
    });
</script>
{% endblock %}

Django/mypyweb/pyweb/templates/common/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <section id="login">
      <div class="row">
          <div class="col-4">
              <h4>로그인</h4>
          </div>
          <div class="col-8 text-end">
              <span>
                  또는 <a href="{% url 'common:signup' %}">계정을 만드세요</a>
              </span>
          </div>
      </div>
      <!--로그인 폼-->
      <form action="" method="post">
          {% csrf_token %}
          {% include 'form_errors.html' %}
          <div class="form-group">
              <label for="username">사용자ID</label>
              <input type="text" id="username" name="username"
                    class="form-control"
                    value="{{ form.username.value|default_if_none:'' }}">
          </div>
          <div class="form-group">
              <label for="password">비밀번호</label>
              <input type="password" id="password" name="password"
                    class="form-control"
                    value="{{ form.password.value|default_if_none:'' }}">
          </div>
          <button type="submit" class="btn btn-primary">로그인</button>
      </form>
  </section>
</div>
{% endblock %}

Django/mypyweb/pyweb/templates/form_errors.html
<!--유효성 검사 - 오류 처리 시작-->
{% if form.errors %}
    <div class="alert alert-danger">
    {% for field in form %}   <!-- 폼을 필드를 순회하면서  -->
        {% if field.errors %} <!-- 필드에 오류가 있으면 -->
        <strong>{{ field.label }}</strong>
            {{ field.errors }}  <!-- 에러 출력 -->
        {% endif %}
    {% endfor %}
    </div>
{% endif %}
<!-- 오류 처리 끝-->

Django/mypyweb/pyweb/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Pyweb</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          {% if user.is_authenticated %}  <!-- 로그인 되었으면 -->
          <a class="nav-link" href="{% url 'common:logout' %}">
              {{ user.username }}(로그아웃)
          </a>
          {% else %}
              <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
          {% endif %}
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page"
             href="{% url 'board:question_list' %}">질문/답변</a>
        </li>
      </ul>
    </div>
  </div>
</nav>