Django/mypyweb/pyshop/cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.detail, name='detail'), # 장바구니 상세
    path('add/<int:product_id>/', views.add, name='product_add'), #장바구니 제품 추가
    path('remove/<int:product_id>/', views.remove, name='product_remove') #장바구니 제품 삭제

]

Django/mypyweb/pyshop/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from shop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

Django/mypyweb/pyshop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_in_category, name='product_all'),
    path('<slug:category_slug>/', views.product_in_category, name='product_in_category'),
    path('<int:id>/<slug:product_slug>/', views.product_detail, name='product_detail')
]

Django/mypyweb/pyshop/cart/models.py
from django.db import models

# Create your models here.

Django/mypyweb/pyshop/shop/models.py
from django.db import models

from django.urls import reverse


#Category 모델
class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, unique=True)
    meta_description = models.TextField(blank=True)
    slug = models.SlugField(max_length=100, db_index=True,
                            unique=True, allow_unicode=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):  #product 페이지 경로
        return reverse('shop:product_in_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True, unique=True, allow_unicode=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True)
    description = models.TextField(blank=True)  #제품 상세설명
    meta_description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2) #소수 2째자리까지
    stock = models.PositiveIntegerField() #재고 수량
    available_display = models.BooleanField('Display', default=True)
    available_order = models.BooleanField('Order', default=True)

    created = models.DateTimeField(auto_now_add=True) #상품 등록일
    updated = models.DateTimeField(auto_now=True) #수정일

    class Meta:
        ordering = ['-created', '-updated']
        index_together = [['id', 'slug']] #index 기준으로 혼합 사용

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

Django/mypyweb/pyshop/cart/forms.py
from django import forms

# 클라이언트가 화면에서 입력하는 폼
class AddProductForm(forms.Form):
    quantity = forms.IntegerField()  #수량
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

Django/mypyweb/pyshop/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from cart.cart import Cart
from cart.forms import AddProductForm
from shop.models import Product


# 장바구니 상세 페이지
def detail(request):
    cart = Cart(request) # 장바구니 객체 생성

    for product in cart:
        product['quantity_form'] = AddProductForm(
            initial={'quantity': product['quantity'],
                     'id_update': True}
        )
    context = {'cart': cart}
    return render(request, 'cart/detail.html', context)

# 장바구니에 제품 추가
@require_POST
def add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = AddProductForm(request.POST) #입력된 수량
    if form.is_valid():
        cd = form.cleaned_data #유효성 검사가 끝난 데이터
        cart.add(product=product, quantity=cd['quantity'],
                 is_update=cd['is_update'])
    return redirect('cart:detail')

def remove(request, product_id):
    cart = Cart(request)
    # 삭제할 제품 1개 가져옴
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')

Django/mypyweb/pyshop/shop/views.py
from django.shortcuts import render, get_object_or_404

from cart.forms import AddProductForm
from shop.models import Category, Product


def index(request):
    return render(request, 'shop/index.html')

def product_in_category(request, category_slug=None):
    current_category = None
    categories = Category.objects.all() #카테고리 목록(전체)
    products = Product.objects.filter(available_display=True)

    if category_slug:
        # 현재 카테고리 1개 가져옴
        current_category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=current_category)

    context = {
        'current_category': current_category,
        'categories': categories,
        'products': products
    }
    return render(request, 'shop/list.html', context)

#상세 페이지
def product_detail(request, id, product_slug=None):
    product = get_object_or_404(Product, id=id, slug=product_slug)
    add_to_cart = AddProductForm(initial={'quantity':1})
    context = {
        'product' : product,
        'add_to_cart' : add_to_cart
    }
    return render(request, 'shop/detail.html', context)

Django/mypyweb/pyshop/templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>hello~</title>
    <link rel="stylesheet" href="{% static 'shop/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'shop/css/style.css' %}">
    <script src="{% static 'shop/js/bootstrap.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
</head>
<body>
{% include 'navbar.html' %}
<!--    본문 내용 start-->
<div class="container my-3">
{% block content %}

{% endblock %}
</div>
<!--본문 내용 end-->

<!-- 제이쿼리 영역 -->
{% block script %}

{% endblock %}
</body>
</html>

Django/mypyweb/pyshop/templates/cart/detail.html
{% extends 'base.html' %}

{% block content %}
<section id="detail">
    <h1>장바구니 상세 페이지</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
                <!--{% with product=item.product %}-->
            <tr>
                <td>
                    <a href="{{ item.product.get_absolute_url }}">
                        <img src="{{ item.product.image.url }}" class="img-thumbnail">
                    </a>
                </td>
                <td>{{ item.product.name }}</td>
                <td>
                    <form action="{% url 'cart:product_add' product.id%}" method="post">
                        {% csrf_token %}
                        {{ item.quantity_form.quantity }}
                        {{ item.quantity_form.is_update }}
                        <input type="submit" value="Update" class="btn btn-primary mt-1">
                    </form>
                </td>
                <td><a href="{% url 'cart:product_remove' product.id %}">Remove</a></td>
                <td>{{ item.price }}</td>
                <td>{{ item.total_price }}</td>
            </tr>
                <!--{% endwith %}-->
        {% endfor %}
        <tr>
            <td>Total</td>
            <td colspan="4"></td>
            <td>{{ cart.get_product_total }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-end">
        <a href="{% url 'shop:product_all' %}" class="btn btn-secondary">Continue Shopping</a>
    </p>
</section>

{% endblock %}

Django/mypyweb/pyshop/templates/form_errors.html
<!--유효성 검사 - 오류 처리 시작-->
{% if form.errors %}
    {% for field in form %}   <!-- 폼을 필드를 순회하면서  -->
        {% if field.errors %} <!-- 필드에 오류가 있으면 -->
        <div class="alert alert-danger">
            <strong>{{ field.label }}</strong>
            {{ field.errors }}  <!-- 에러 출력 -->
        </div>
        {% endif %}
    {% endfor %}

    <!--넌 필드 오류-->
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>   <!--데이터베이스 오류-->
        </div>
    {% endfor %}
{% endif %}
<!-- 오류 처리 끝-->

Django/mypyweb/pyshop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Pyshop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="">로그인</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:product_all' %}">shop</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:detail' %}">Cart</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

Django/mypyweb/pyshop/templates/shop/detail.html
{% extends 'base.html' %}

{% block content %}
<section id="detail">
    <div class="row">
        <div class="col-4">
            <img src="{{ product.image.url }}" width="100%">
        </div>
        <div class="col">
            <h1 class="display-6">{{ product.name }}</h1>
            <p><span class="badge bg-dark">Price</span>{{ product.price }}</p>
            <form action="{% url 'cart:product_add' product.id %}" method="post">
                {% csrf_token %}
                {{ add_to_cart }}
                <input type="submit" value="Add to Cart" class="btn btn-primary btn-sm">
            </form>
            <h5><span class="badge bg-secondary">Description</span>
                <!--|linebreaks : 템플릿 태그 - 줄바꿈-->
                {{ product.description|linebreaks }}
            </h5>
        </div>
    </div>
</section>
{% endblock %}

Django/mypyweb/pyshop/templates/shop/index.html
{% extends 'base.html' %}

{% block content %}
<section id="index">
    <h1>안녕하세요~ 좋은 쇼핑몰입니다.</h1>

</section>

{% endblock %}

Django/mypyweb/pyshop/templates/shop/list.html
{% extends 'base.html' %}

{% block content %}
<section id="list">
    <div class="row">
        <!--2: 10 - 분류: 상품-->
        <div class="col-2">
            <div class="list-group">
                <a href="{% url 'shop:product_all' %}" class="list-group-item
                        {% if not current_category %} active {% endif %}">All</a>

                {% for category in categories %}
                    <a href="{{ category.get_absolute_url }}"
                        class="list-group-item {% if current_category.slug == category.slug %} active {% endif %}">
                        {{ category.name }}</a>
                {% endfor %}
            </div>
        </div>
        <!--제품-->
        <div class="col-10">
            <div class="alert alert-info">
                {% if current_category %}
                    {{ current_category.name }}
                {% else %}
                    All Products
                {% endif %}
            </div>
            <div class="row">

            {% for product in products %}
            <div class="col-4">

                <div class="card">
                    <img class="card-img-top" src="{{ product.image.url }}" alt="Product Image">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">
                            {{ product.description }}
                            <span class="badge bg-dark">
                                {{ product.price }}
                            </span>
                        </p>
                        <a href="{{ product.get_absolute_url }}" class="btn btn-success">View Detail</a>
                    </div>
                </div>

            </div>
            {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock %}